/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppLoginRouteImport } from './routes/app.login'
import { Route as AppDirectorRouteImport } from './routes/app.director'
import { Route as AppCreateRouteImport } from './routes/app.create'
import { Route as AppChangePasswordRouteImport } from './routes/app.change-password'
import { Route as AppAssetsRouteImport } from './routes/app.assets'
import { Route as AppEditorProjectIdRouteImport } from './routes/app.editor.$projectId'
import { Route as AppDirectorHelpRouteImport } from './routes/app.director.help'
import { Route as AppDirectorProjectIdRouteImport } from './routes/app.director.$projectId'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminProvidersRouteImport } from './routes/app.admin.providers'
import { Route as AppAdminModelsRouteImport } from './routes/app.admin.models'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectorRoute = AppDirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppChangePasswordRoute = AppChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorProjectIdRoute = AppEditorProjectIdRouteImport.update({
  id: '/editor/$projectId',
  path: '/editor/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectorHelpRoute = AppDirectorHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppDirectorRoute,
} as any)
const AppDirectorProjectIdRoute = AppDirectorProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppDirectorRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminProvidersRoute = AppAdminProvidersRouteImport.update({
  id: '/admin/providers',
  path: '/admin/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminModelsRoute = AppAdminModelsRouteImport.update({
  id: '/admin/models',
  path: '/admin/models',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/assets': typeof AppAssetsRoute
  '/app/change-password': typeof AppChangePasswordRoute
  '/app/create': typeof AppCreateRoute
  '/app/director': typeof AppDirectorRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/app/admin/models': typeof AppAdminModelsRoute
  '/app/admin/providers': typeof AppAdminProvidersRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/director/$projectId': typeof AppDirectorProjectIdRoute
  '/app/director/help': typeof AppDirectorHelpRoute
  '/app/editor/$projectId': typeof AppEditorProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/assets': typeof AppAssetsRoute
  '/app/change-password': typeof AppChangePasswordRoute
  '/app/create': typeof AppCreateRoute
  '/app/director': typeof AppDirectorRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/app/admin/models': typeof AppAdminModelsRoute
  '/app/admin/providers': typeof AppAdminProvidersRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/director/$projectId': typeof AppDirectorProjectIdRoute
  '/app/director/help': typeof AppDirectorHelpRoute
  '/app/editor/$projectId': typeof AppEditorProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/assets': typeof AppAssetsRoute
  '/app/change-password': typeof AppChangePasswordRoute
  '/app/create': typeof AppCreateRoute
  '/app/director': typeof AppDirectorRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/app/admin/models': typeof AppAdminModelsRoute
  '/app/admin/providers': typeof AppAdminProvidersRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/director/$projectId': typeof AppDirectorProjectIdRoute
  '/app/director/help': typeof AppDirectorHelpRoute
  '/app/editor/$projectId': typeof AppEditorProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/assets'
    | '/app/change-password'
    | '/app/create'
    | '/app/director'
    | '/app/login'
    | '/app/admin/models'
    | '/app/admin/providers'
    | '/app/admin/users'
    | '/app/director/$projectId'
    | '/app/director/help'
    | '/app/editor/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/assets'
    | '/app/change-password'
    | '/app/create'
    | '/app/director'
    | '/app/login'
    | '/app/admin/models'
    | '/app/admin/providers'
    | '/app/admin/users'
    | '/app/director/$projectId'
    | '/app/director/help'
    | '/app/editor/$projectId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/assets'
    | '/app/change-password'
    | '/app/create'
    | '/app/director'
    | '/app/login'
    | '/app/admin/models'
    | '/app/admin/providers'
    | '/app/admin/users'
    | '/app/director/$projectId'
    | '/app/director/help'
    | '/app/editor/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/director': {
      id: '/app/director'
      path: '/director'
      fullPath: '/app/director'
      preLoaderRoute: typeof AppDirectorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/change-password': {
      id: '/app/change-password'
      path: '/change-password'
      fullPath: '/app/change-password'
      preLoaderRoute: typeof AppChangePasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets': {
      id: '/app/assets'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor/$projectId': {
      id: '/app/editor/$projectId'
      path: '/editor/$projectId'
      fullPath: '/app/editor/$projectId'
      preLoaderRoute: typeof AppEditorProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/director/help': {
      id: '/app/director/help'
      path: '/help'
      fullPath: '/app/director/help'
      preLoaderRoute: typeof AppDirectorHelpRouteImport
      parentRoute: typeof AppDirectorRoute
    }
    '/app/director/$projectId': {
      id: '/app/director/$projectId'
      path: '/$projectId'
      fullPath: '/app/director/$projectId'
      preLoaderRoute: typeof AppDirectorProjectIdRouteImport
      parentRoute: typeof AppDirectorRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/providers': {
      id: '/app/admin/providers'
      path: '/admin/providers'
      fullPath: '/app/admin/providers'
      preLoaderRoute: typeof AppAdminProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/models': {
      id: '/app/admin/models'
      path: '/admin/models'
      fullPath: '/app/admin/models'
      preLoaderRoute: typeof AppAdminModelsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppDirectorRouteChildren {
  AppDirectorProjectIdRoute: typeof AppDirectorProjectIdRoute
  AppDirectorHelpRoute: typeof AppDirectorHelpRoute
}

const AppDirectorRouteChildren: AppDirectorRouteChildren = {
  AppDirectorProjectIdRoute: AppDirectorProjectIdRoute,
  AppDirectorHelpRoute: AppDirectorHelpRoute,
}

const AppDirectorRouteWithChildren = AppDirectorRoute._addFileChildren(
  AppDirectorRouteChildren,
)

interface AppRouteChildren {
  AppAssetsRoute: typeof AppAssetsRoute
  AppChangePasswordRoute: typeof AppChangePasswordRoute
  AppCreateRoute: typeof AppCreateRoute
  AppDirectorRoute: typeof AppDirectorRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  AppAdminModelsRoute: typeof AppAdminModelsRoute
  AppAdminProvidersRoute: typeof AppAdminProvidersRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppEditorProjectIdRoute: typeof AppEditorProjectIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssetsRoute: AppAssetsRoute,
  AppChangePasswordRoute: AppChangePasswordRoute,
  AppCreateRoute: AppCreateRoute,
  AppDirectorRoute: AppDirectorRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  AppAdminModelsRoute: AppAdminModelsRoute,
  AppAdminProvidersRoute: AppAdminProvidersRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppEditorProjectIdRoute: AppEditorProjectIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
