onlyBuiltDependencies:
  - esbuild
  - lightningcss
  - unrs-resolver
allowBuilds:
  esbuild: true
  lightningcss: true
  unrs-resolver: true
overrides:
  js-yaml: 4.3.1
  nanoid: 3.3.18
  postcss: 8.5.23
